# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ab07cf88f4c83e8258531bca51d8ad0f08a46ef407bf94029f6e8e36344ac20f0b448c333736ecd94ba1a6833d91291f2fb42aa7478264c0b9954043a05a78

test:
  secret_key_base: dab95e026441d68dc4cbde4ad8a6807cd4e85e98f4775158cf611e0ec2f7fdd7d340584ce80c79fbc22695b6148366a3cdd9f237db845faeabbc14ce6120addc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
